# content of: tox.ini , put in same dir as setup.py
[tox]
envlist =
    py311
    py312
    ; py313 ; missing native libs

[testenv]
deps =
    # parameterized
    pytest==7.4.4
    pytest-cov==4.1.0
    hypothesis>=6.96.0
    pytest-snapshot
    pytest-asyncio
    pytest-network
    toml

commands =
    py.test --cov-report term-missing --cov=activist --ignore=on_hold
